SELECT BOOK.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY,
SUM(BOOK.PRICE * BOOK_SALES.SALES) AS TOTAL_SALES
FROM BOOK
JOIN AUTHOR USING(AUTHOR_ID)
JOIN BOOK_SALES USING(BOOK_ID)
WHERE BOOK_SALES.SALES_DATE LIKE '2022-01%'
GROUP BY AUTHOR.AUTHOR_NAME, BOOK.CATEGORY
ORDER BY BOOK.AUTHOR_ID ASC, BOOK.CATEGORY DESC;