WITH TEMP AS (
    SELECT USER_ID, SALES_DATE AS SALES_DATE, GENDER, COUNT(DISTINCT USER_ID) AS count
    FROM ONLINE_SALE
    LEFT JOIN USER_INFO USING (USER_ID)
    WHERE GENDER IS NOT NULL
    GROUP BY DATE_FORMAT(SALES_DATE, '%Y-%m'), GENDER
    ORDER BY SALES_DATE ASC, USER_ID ASC
)

SELECT YEAR(TEMP.SALES_DATE) AS YEAR, MONTH(TEMP.SALES_DATE) AS MONTH, GENDER, TEMP.count AS USERS
FROM TEMP
ORDER BY YEAR ASC, MONTH ASC, GENDER ASC;