WITH RECURSIVE CTE (hour) AS
(   
    SELECT 0 
    UNION ALL
    SELECT hour + 1 FROM CTE WHERE hour < 23
)

SELECT hour AS HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM CTE
LEFT JOIN ANIMAL_OUTS ON hour = HOUR(DATETIME)
GROUP BY hour
ORDER BY HOUR ASC;