WITH TOTAL_SALES_PER_USER AS
(
SELECT WRITER_ID, SUM(PRICE) AS TOTAL
FROM USED_GOODS_BOARD
WHERE STATUS = 'DONE'
GROUP BY WRITER_ID
HAVING TOTAL >= 700000
)

SELECT U.USER_ID, U.NICKNAME, T.TOTAL AS TOTAL_SALES
FROM USED_GOODS_USER U
JOIN TOTAL_SALES_PER_USER T ON U.USER_ID = T.WRITER_ID
ORDER BY TOTAL_SALES ASC;