WITH OVER_FIVE_RENT_CARS AS (
    SELECT MONTH(START_DATE) AS MONTH, CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
)

SELECT O.MONTH, O.CAR_ID, COUNT(*) AS RECORDS
FROM OVER_FIVE_RENT_CARS O
WHERE (
    SELECT COUNT(*)
    FROM OVER_FIVE_RENT_CARS A
    WHERE O.CAR_ID = A.CAR_ID) >= 5
GROUP BY O.MONTH, O.CAR_ID
ORDER BY O.MONTH ASC, O.CAR_ID DESC;